[ALPS07713407] 8250: fix incompatible function pointer types
Follow commit bec5b814d46c ("serial: Make ->set_termios() old ktermios const")
to fix the following build breaks:

drivers/tty/serial/8250/8250_mtk.c:1843:24: error: incompatible function pointer types assigning to void (*)(struct uart_port *, struct ktermios *, const struct ktermios *) from void (struct uart_port *, struct ktermios *, struct ktermios *) [-Werror,-Wincompatible-function-pointer-types]

MTK-Commit-Id: af10069b8e55686d3443b16a031cbefaddec18dc

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I58d283a8791fa79c9e5fa7eb5239967c3cef490e