[ALPS07673475] spi: change remove function to a void function
commit a0386bba7093 ("spi: make remove callback a void function") makes
remove callback a void function, change them accordingly.

drivers/input/touchscreen/GT9896S/goodix_ts_spi.c:1397:12: error: incompatible function pointer types initializing void (*)(struct spi_device *) with an expression of type int (struct spi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/input/touchscreen/GT9895/goodix_brl_spi.c:314:12: error: incompatible function pointer types initializing void (*)(struct spi_device *) with an expression of type int (struct spi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/nfc/st54spi.c:1416:12: error: incompatible function pointer types initializing void (*)(struct spi_device *) with an expression of type int (struct spi_device *) [-Werror,-Wincompatible-function-pointer-types]

MTK-Commit-Id: 0e6f78c3ef0860f30d3fac375c214db9769b27d7

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ib6d11d809f5f8653cdd9ff0cd7c35fe2d5356fd8