[ALPS07673475] eccci: fix incorrect headers
commit 4721031c3559 ("net: move gro definitions to include/net/gro.h")
move gro definitions to include/net/gro.h, so include include/net/gro.h
to fix the following build breaks

drivers/misc/mediatek/eccci/hif/ccci_dpmaif_com.c:424:23: error: member reference type int is not a pointer

MTK-Commit-Id: 7c74fa2d3de71c09204d9eaf11e9301cc69a81af

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ifc3fd203738dac408bb0ce3b92d359d8b86b5ad8