[ALPS07673475] sched: fix incomplete definition of struct cpuidle_state
Include linux/cpuidle.h to fix the following build breaks

drivers/misc/mediatek/sched/fair.c:616:21: error: incomplete definition of type struct cpuidle_state
drivers/misc/mediatek/sched/fair.c:629:25: error: incomplete definition of type struct cpuidle_state

MTK-Commit-Id: 11b35f1863205936f2301df3925b5efa32529040

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Iccdd945e5a83b86f240e13bf484a170168071fb8