[ALPS07673475] ufs: mediatek: call scsi_done directly
Follow commit: 11b68e36b167 ("scsi: core: Call scsi_done directly")
to fix the following build error:

drivers/scsi/ufs/vendor/../ufs-mediatek-mcq.c:188:8: error: no member named scsi_done in struct scsi_cmnd

MTK-Commit-Id: 665e88390c19111d4fd7cb2f6941155c66955955

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I25aeaad7300367cdab2f8d1bbd28b7c4dfed36f0