[ALPS07713407] media: isp: fix media_entity build breaks
Follow commit 9e3576a1ae2b ("media: mc: convert pipeline funcs to take media_pad"),
convert pipeline arg to media_pad to fix the following build breaks:

drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8729:29: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8786:22: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8838:22: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8732:29: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6669:29: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6722:22: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6770:22: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/imgsys/mtk_imgsys-v4l2.c:574:30: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/imgsys/mtk_imgsys-v4l2.c:617:22: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]
drivers/media/platform/mtk-isp/imgsys/mtk_imgsys-v4l2.c:657:23: error: incompatible pointer types passing struct media_entity * to parameter of type struct media_pad * [-Werror,-Wincompatible-pointer-types]

MTK-Commit-Id: f7eb46d41903f01efa61b33d164729e80f753e50

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I4736662351a6d0966065c591b07273de65d71818