[ALPS07673475] drm: drm: remove allow_fb_modifiers build breaks
commit 3d082157a242 ("drm: remove allow_fb_modifiers") remove allow_fb_modifiers,
so remove it to fix the following build breaks

errors:
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:5353:19: error: no member named allow_fb_modifiers in struct drm_mode_config

MTK-Commit-Id: 72e51b526dd75aacd44933115382daafbea19bad

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: If5f77577a1755d5eb2fd130189a7dfef498cd42d