[ALPS07673475] seneor: fix type specifier missing
Add type specifier to fix the following build breaks

drivers/misc/mediatek/sensor/2.0/sensorhub/transceiver.c:650:8: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]

MTK-Commit-Id: cefed4df5b1bbe7fd4489441b5a9b9f1f0c32077

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ic9a802f29528e5dca8e88b5fec14489c346ab031