[ALPS07673475] ccmni: use rtnl_link_stats64
commit 625788b58445 ("net: add per-cpu storage and net->core_stats") removed
rx_dropped, use rtnl_link_stats64 to read the core counter and fix the following
build breaks

Errors:
drivers/misc/mediatek/ccmni/ccmni.c:1495:30: error: no member named rx_dropped in struct net_device
drivers/misc/mediatek/ccmni/ccmni.c:1510:30: error: no member named rx_dropped in struct net_device

MTK-Commit-Id: 086b5f71304f30c1738f8caca3e804762c1b8aa8

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I67b8b7f1b53c8fffd647e157911f877d7e9af991