[ALPS07673475] spi: use GPIO descriptors
Follow commit 1a5a87d541b4 ("spi: mt65xx: Convert to GPIO descriptors").

drivers/spi/spi-mt65xx.c:831:58: error: no member named cs_gpio in struct spi_device; did you mean cs_gpiod?
drivers/spi/spi-mt65xx.c:832:30: error: no member named cs_gpio in struct spi_device; did you mean cs_gpiod?

MTK-Commit-Id: 0fe81c5ed712214022c77dbb348e93e024129ff2

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I9e20054ed01bc16dbe6c5e451e010e27b89e59da