[ALPS07713407] drm/mediatek: fix drm/drm_gem_cma_helper.h not found
Follow commit 4a83c26a1d87 ("drm/gem: rename GEM CMA helpers to GEM DMA helpers")
to rename cma to dma and fix the following build errors:

drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_gem.c:11:10: fatal error: drm/drm_gem_cma_helper.h file not found
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_drv.c:10:10: fatal error: drm/drm_gem_cma_helper.h file not found

MTK-Commit-Id: e0aeff1c363c946df065ed47b8115591fd7f7a00

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I4d4452d1833fac0ccf235fa4b32d7f24ebea2888