[ALPS07673475] eas: fix cpu_util_cfs argument
commit: 82762d2af31a ("sched/fair: Replace CFS internal cpu_util()
with cpu_util_cfs()") replace cpu_util_cfs(rq) with cpu_util_cfs(cpu).
Change it accordingly to fix the following build breaks:

Errors:
drivers/misc/mediatek/sched/eas/eas_plus.c:871:34: error: incompatible pointer to integer conversion passing struct rq * to parameter of type int [-Werror,-Wint-conversion]
drivers/misc/mediatek/sched/sugov/cpufreq_sugov_main.c:331:40: error: incompatible pointer to integer conversion passing struct rq * to parameter of type int [-Werror,-Wint-conversion]

MTK-Commit-Id: d8e4d1d8b2ce90ffb2e5755dd43dd1ce9356532c

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I1f1400d56512882b166c65963afa51e4536cbd77