[ALPS07673475] eas: mask out unused function mtk_check_d_tasks
Mask out mtk_check_d_tasks to fix the following build breaks:

Errors:
drivers/misc/mediatek/sched/eas/sched_main.c:123:13: error: unused function mtk_check_d_tasks [-Werror,-Wunused-function]

MTK-Commit-Id: bffe52de241fb50308e9dc0c637564dad4041215

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ibe976b4b798c9fa76b7fdec404d5fb4b8a5f980e