[ALPS07673475] eas: fix hk_flags build breaks
commit 04d4e665a609 ("sched/isolation: Use single feature type while referring to housekeeping cpumask")
changes hk_flags to kh_type, fix them accordingly.

Errors:
drivers/misc/mediatek/sched/eas/core_pause.c:496:29: error: use of undeclared identifier HK_FLAG_TIMER
drivers/misc/mediatek/sched/eas/core_pause.c:508:33: error: use of undeclared identifier HK_FLAG_TIMER
drivers/misc/mediatek/sched/eas/core_pause.c:586:33: error: use of undeclared identifier HK_FLAG_MISC

MTK-Commit-Id: e28a890cdcec0fec964488c40b591fd51e0922fa

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I507466befdb9dcfa9075e5c0e25c0652464038ea