[ALPS07673475] watchdog: fix mt2712-resets.h not found build breaks
Follow commit f07c776f6d7e ("arm64: dts: mediatek: Move reset controller constants into common location")
to fix the following build breaks

drivers/watchdog/mtk_wdt.c:12:10: fatal error: dt-bindings/reset-controller/mt2712-resets.h file not found

MTK-Commit-Id: e3f5b59fa8654384d5d6198f928f459650bef4cf

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I179d4258f202c9b5587332d70e43efe3dd05142a