[ALPS07689827] usb_meta: fix build error
commit af1969a2d734d renames usb_gadget_probe_driver() to usb_gadget_register_driver()

drivers/misc/mediatek/usb/usb_meta/usb_meta.c:1385:8: error: implicit declaration of function usb_gadget_probe_driver is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 02c52868fc5f7419517122062329f7fb14750698

CR-Id: ALPS07689827
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: I3a5492f2091c28fe050f4d27f6ef04da67bf2cee