[ALPS07673475] aee: fix no member named cpu in struct task_struct
commit bcf9033e5449 ("sched: move CPU field back into thread_info if THREAD_INFO_IN_TASK=y")
move cpu to thread_info, fix it accordingly.

Error:
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_01_13_00-latest/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/aee/hangdet/hangdet.c:367:40: error: no member named cpu in struct task_struct

MTK-Commit-Id: 80184977c645d45220596a41fe6ec2ca8647ae54

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I5d4f921929a392018625956ac20a611fb72f1ca2