[ALPS07713407] iio: adc: fix of_xlate build breaks
Follow commit 34b6eb89351b ("iio: adc: at91-sama5d2_adc: convert to device properties")
to fix the following build breaks

drivers/iio/adc/mt6338-auxadc.c:276:3: error: field designator of_xlate does not refer to any field in type const struct iio_info
drivers/iio/adc/mtk-spmi-pmic-adc.c:407:3: error: field designator of_xlate does not refer to any field in type const struct iio_info
drivers/iio/adc/mt635x-auxadc.c:327:3: error: field designator of_xlate does not refer to any field in type const struct iio_info

MTK-Commit-Id: 6ac8e6db3bfc70bf51a9651cb9b505e3f754607e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I8a993edf3953d3d877cd63cbbdd1b3748dfc5ae5