[ALPS07673475] vcodec: fix implicit-fallthrough build breaks
Fix the following unannotated fall-through errors:

drivers/media/platform/mtk-vcodec/venc/venc_vcp_if.c:511:3: error:
unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

MTK-Commit-Id: 9457a57f864c42537e29afa3fc9a4f532bc72b90

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Id648e0927d045681a1178085ff58c019dd091faf