[ALPS07673475] aee: fix implicit declaration of sched_show_task
include linux/sched/debug.h to fix the following build breaks:

Error:
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_01_13_00-latest/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/aee/hangdet/hangdet.c:368:4: error: implicit declaration of function sched_show_task is invalid in C99 [-Werror,-Wimplicit-function-declaration]
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_01_13_00-latest/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/aee/hangdet/hangdet.c:379:4: error: implicit declaration of function sched_show_task is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: fdcbfdd0835f71af1d4cad52079421235ff5d68c

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: If7259609c78a77b170de6bf3a029c064eed3525c