[ALPS07713407] iommu/mediatek: clean up bus_set_iommu()
Follow commit 7341c365c3fb ("iommu/mtk: Clean up bus_set_iommu()")
to remove the usage of bus_set_iommu

drivers/iommu/mtk_iommu.c:2895:9: error: call to undeclared function bus_set_iommu; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/iommu/mtk_iommu.c:2951:2: error: call to undeclared function bus_set_iommu; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/iommu/mtk_iommu.c:2972:3: error: call to undeclared function bus_set_iommu; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: f82f92f55b42b9cd6be98cf92023650f9ddd9792

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I4928b356597a7b9872cc4930672ff78eee375ae6