[ALPS07713407] media: isp: comment out pipe switching logic
With commit ae219872834a ("media: mc: entity: Rewrite media_pipeline_start()"),
I think we should use pipe_start/stop APIs, however, some part
of the isp code switch the pipeline and I cannot find a proper way
to switch two pipelines.

Leave it to the camera forks

Errors:
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c::739739::4949::  error: error: no member named pipe in struct media_entityno member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c:740:40:/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c :error: 740no member named pipe in struct media_entity:

drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c:741:40: error: /mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.cno member named pipe in struct media_entity:

drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c::742743::4140: :error:  error: no member named pipe in struct media_entityno member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c::743744::4040::  error: error: no member named pipe in struct media_entityno member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-ctrl.c:744:40: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8864:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8865:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8868:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8869:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8861:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8862:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8865:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8866:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:748:49: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:749:40: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:750:40: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:751:41: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:752:40: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:753:40: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6798:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6799:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6802:16: error: no member named pipe in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6803:16: error: no member named pipe in struct media_entity

MTK-Commit-Id: 694902a69285b57d5b78b915354f5aa969bc4466

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I2ea461e694ea3006e260c0e54674ccb701becfdc