[ALPS07713407] kernel_device_modules: fix i2c remove callback return type
Follow commit ed5c2f5fd10d ("i2c: Make remove callback return void")
to change return type of remove function to void and
fix the following build breaks:

drivers/misc/mediatek/lens/ois/bu63169/bu63169.c:399:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3643.c:1027:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/mfd/rt9490.c:316:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/nfc/st21nfc/st21nfc.c:1252:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/gt9764/gt9764.c:399:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/gate_ic/rt4831a_drv.c:366:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/gt9772a/gt9772a.c:401:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
sound/soc/mediatek/common/mtk-sp-spk-amp.c:276:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/lc898229/lc898229.c:408:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/cam_cal/src/custom/../common/v2/eeprom_driver.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/flashlight/v4l2/k6983v1_64_alpha/sy7806.c::455929::1612::  error: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/flashlight/v4l2/lm3644.c:1061:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/dw9718/dw9718.c:442:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/mfd/mt6375.c:480:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/mfd/mt6338-core.c:263:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main3/main3_lens.c:575:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/regulator/rt5133-regulator.c:660:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub/sub_lens.c:577:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/gt9772b/gt9772b.c:401:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
sound/soc/codecs/richtek/rt5512.c:1238:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/power/supply/rt9759.c:1947:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/ak7377a/ak7377a.c:416:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/dw9800w/dw9800w.c:420:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/typec/tcpc/tcpc_mt6360.c:2575:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/sub2/sub2_lens.c:570:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main2/main2_lens.c:595:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/proprietary/main/main_lens.c:644:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/ak7375c/ak7375c.c:405:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c::6668207::2913::  error: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:219:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:231:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-trunk-u0.bsp--2022_11_14_13_00-verify/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:244::667713::25 :error:  incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:258:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:272:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:286:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:300:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
sound/soc/codecs/tfa98xx/src/tfa98xx.c:3249:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/typec/tcpc/tcpc_rt1711h.c:1615:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/bu64253gwz/bu64253gwz.c:426:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/input/touchscreen/k6985v1_64_alpha/samsung_y761/sec_ts.c:4014:13: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/power/supply/rt9758-charger.c:727:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:1513:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/misc/mediatek/lens/vcm/v4l2/dw9800v/dw9800v.c:516:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/mtk_drm_panel_i2c.c:143:12: error: incompatible function pointer types initializing void (*)(struct i2c_client *) with an expression of type int (struct i2c_client *) [-Werror,-Wincompatible-function-pointer-types]

MTK-Commit-Id: 6807ea5959c3bb07fc94eadf3b21d5cacb1f8516

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ia9824d3d3f16aefb196b81519708b77e113fbc10