[ALPS07673475] spi: use GPIO descriptors
Follow commit 1a5a87d541b4 ("spi: mt65xx: Convert to GPIO descriptors").

drivers/spi/spi-mt65xx.c:832:25: error: incompatible pointer to integer conversion passing struct gpio_desc * to parameter of type unsigned int [-Werror,-Wint-conversion]
drivers/spi/spi-mt65xx.c:1085:16: error: no member named cs_gpios in struct spi_controller; did you mean cs_gpiods?
drivers/spi/spi-mt65xx.c:1092:15: error: no member named cs_gpios in struct spi_controller; did you mean cs_gpiods?
drivers/spi/spi-mt65xx.c:1095:16: error: no member named cs_gpios in struct spi_controller; did you mean cs_gpiods?
drivers/spi/spi-mt65xx.c:1095:8: error: incompatible pointer to integer conversion passing struct gpio_desc * to parameter of type unsigned int [-Werror,-Wint-conversion]

MTK-Commit-Id: 508d1588a45dc199656309951ff2a26401c3c6fc

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I32802ee74d021dc9a8c3f249b200ec28a13dd721