[ALPS07673475] eas: fix incomplete type struct sched_param build breaks
include uapi/linux/sched/types.h to fix the following build breaks:

Errors:
drivers/misc/mediatek/sched/eas/core_pause.c:607:21: error: variable has incomplete type struct sched_param

MTK-Commit-Id: 6f869c3aefd48682958b67c10d69ea0c0c5c0ba8

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I5266ae8f23acbef18d8ffd4be4cdf18be19e30ac