[ALPS07673475] drm: DRM_DP_HELPER
commit adb9d5a2c introduced DRM_DP_HELPER

To address error:
ERROR: modpost: "drm_dp_aux_register" [../kernel/kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mediatek-drm.ko] undefined!
ERROR: modpost: "drm_dp_aux_init" [../kernel/kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mediatek-drm.ko] undefined!
ERROR: modpost: "drm_dp_channel_eq_ok" [../kernel/kernel_device_modules-mainline/drivers/gpu/drm/mediatek/mediatek_v2/mediatek-drm.ko] undefined!

MTK-Commit-Id: e0430a347f03db03a84edf387cf862975df50646

CR-Id: ALPS07673475
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: I6a705c98c2d4174c30eb740f24bdb2c03d63ba50