[ALPS07713407] monitor_hang: fix on_task_stack build breaks
Follow commit d1f684e46bbd ("arm64: stacktrace: rework stack boundary discovery")
to remove the info arg from on_task_stack and fix the following
build breaks:

drivers/misc/mediatek/monitor_hang/hang_unwind.c:33:35: error: too many arguments to function call, expected 3, have 4

MTK-Commit-Id: 42cdb54afa4f134589bda08ff17e4ac3e96a4e08

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I3d6d94fa67378c4f1f75999658e4911e785a0641