[ALPS07673475] arm64: configs: mgk: disable CONFIG_MTK_ADVANCED_80211_MLO
commit 7b0a0e3c3a88 ("wifi: cfg80211: do some rework towards MLO link APIs")
is merged to Linux 6.0-rc1, we are merging 5.18, so just disable
CFG_ADVANCED_80211_MLO as a workaround.

When 6.0-rc1 is merged, we will revert this patch.

vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_init.c:991:13: error: incompatible function pointer types initializing int (*)(struct wiphy *, struct net_device *) with an expression of type int (struct wiphy *, struct net_device *, unsigned int) [-Werror,-Wincompatible-function-pointer-types]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_init.c:993:22: error: incompatible function pointer types initializing int (*)(struct wiphy *, struct net_device *, const u8 *, const struct cfg80211_bitrate_mask *) (aka int (*)(struct wiphy *, struct net_device *, const unsigned char *, const struct cfg80211_bitrate_mask *)) with an expression of type int (struct wiphy *, struct net_device *, unsigned int, const u8 *, const struct cfg80211_bitrate_mask *) (aka int (struct wiphy *, struct net_device *, unsigned int, const unsigned char *, const struct cfg80211_bitrate_mask *)) [-Werror,-Wincompatible-function-pointer-types]
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:10370:64: error: too many arguments to function call, expected 2, have 3
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2426:16: error: no member named ap_mld_addr in struct cfg80211_roam_info
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2430:15: error: no member named ap_mld_addr in struct cfg80211_roam_info
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2433:16: error: no member named links in struct cfg80211_roam_info
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2435:15: error: no member named links in struct cfg80211_roam_info
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2436:15: error: no member named links in struct cfg80211_roam_info
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_kal.c:2437:15: error: no member named links in struct cfg80211_roam_info
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_25_06_00-mainline/merged/kernel/../vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_p2p_kal.c:2670:65: error: too many arguments to function call, expected 2, have 3

MTK-Commit-Id: 9ed5c325c0c9385b26e74c67562d51478caf31af

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I154836bcb7ee727023a183998f492c2fb864ac0c