[ALPS07673475] aee: unannotated fall-through between switch labels
Add fallthrough to fix the unannotated fall-through build breaks

Error:
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:229:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:233:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:236:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:239:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:257:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:261:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:263:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/aee/mrdump/mrdump_panic.c:265:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

MTK-Commit-Id: b6cd9635280c859d391f607ebc0f0fd2e4a1c42f

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I8ccd34f68905ae22fe7401ad6788125776620379