[ALPS07673475] blocktag: fix sched_clok build breaks
include linux/sched/clock.h to fix the following build breaks

drivers/misc/mediatek/blocktag/blocktag-pm-trace.c:108:21: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/fscmd-trace.c:279:17: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/fscmd-trace.c:381:17: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
/drivers/misc/mediatek/blocktag/fscmd-trace.c:409:17: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/fscmd-trace.c:429:17: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/fscmd-trace.c:444:17: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 762e5bcc7ab88571bdb5d5d02c85cc08ce4b9370

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I1b43de27cb1b954e21f16f217636b53b82484a28