[ALPS07673475] kernel: fix missing type specifier
Fix missing type specifier

sound/soc/mediatek/mt6985/mt6985-afe-cm.c:108:1: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]
sound/soc/mediatek/mt6983/mt6983-afe-cm.c:111:1: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]
drivers/tee/teei/500/tz_driver/teei_client_main.c:182:1: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]

MTK-Commit-Id: 720554a547cace53d158ac5dcd87b9e30ecbbd36

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I6b0f606ac60ecaf446664f6409b9c113d7fd81dd