[ALPS07673475] PIC: remove unsupported hooks
Remove unsupported hooks to fix the following build breaks:
drivers/pci/controller/pcie-mediatek-gen3.c:32:10: fatal error: trace/hooks/traps.h file not found

MTK-Commit-Id: a6470903360afd8bc2a4301fdb653325fc2f2b6e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I1711e6485d673789098da4b0d1c2eb3cb751da5a