[ALPS07713407] interconnect: mediatek: fix: icc_provider_del return type
commit 680f8666baf6 ("interconnect: Make icc_provider_del() return void")
changes icc_provider_del() to return type void, so we cannot use
return icc_provider_del() anymore.

Fix the following build breaks by returning 0
drivers/interconnect/mediatek/mtk-emi.c:387:9: error: returning void from a function with incompatible result type int

MTK-Commit-Id: c447adf346c7b6c4d35208298ffcf5441118276a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I8816c81aa5cfaa092bd202cbacff1b04a780d627