[ALPS07689827] heaps: register_shrinker
commit e33c267ab70de4 adds names to shrinkers.

drivers/dma-buf/heaps/deferred-free-helper.c:134:45: error: too few arguments to function call, expected at least 2, have 1
        return register_shrinker(&freelist_shrinker);
               ~~~~~~~~~~~~~~~~~                   ^

MTK-Commit-Id: 171706b657992a62258d638676be055d867e6324

CR-Id: ALPS07689827
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: Ieb0c83fd59ac0f524369d0ace2166fa9d446317a