[ALPS07673475] ISP: fix stream_count build breaks
commit 3056a8e936bb ("media: media-entity: Simplify media_pipeline_start()")
drops the stream_count of struct media_entity.
Fix the users of stream_count accordingly.

drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-raw.c:1014:59: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-raw.c:1031:58: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:7937:16: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:7941:16: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c:576:46: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-ctrl.c:579:46: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:927:59: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:938:58: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:949:34: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:749:46: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-ctrl.c:752:46: error: no member named stream_count in struct media_pipeline; did you mean streaming_count?
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6799:16: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6803:16: error: no member named stream_count in struct media_entity

MTK-Commit-Id: 8d18cebc631ae556d46eafa1ba1f15c90d2983d1

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I697d11ac9443b8b1e84d294639e836dde6207b1b