[ALPS07673475] eas_plus: fix arch_set_thermal_pressure build breaks
commit 65c99af98ba6 ("Revert "ANDROID: sched: avoid placing RT threads on cores handling softirqs"")
removed RT_SOFTINT_OPTIMIZATION and defined task_may_not_preempt in android.h.

commit 5168b1be0905 ("thermal: cpufreq_cooling: Use new thermal pressure update function")
replace arch_set_thermal_pressure with arch_update_thermal_pressure

Errors:
drivers/misc/mediatek/sched/eas/eas_plus.c:53:6: error: redefinition of task_may_not_preempt
drivers/misc/mediatek/sched/eas/eas_plus.c:442:2: error: implicit declaration of function arch_set_thermal_pressure is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 7b00181c8c922a0426ba8c48e8dc267e0fa6141b

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Idec11cbce72572621d57167568b7134b8824cc05