[ALPS07673475] usb: fix get_ether_addr build breaks
Follow commit 99984b081f99 ("usb: gadget: u_ether: use eth_hw_addr_set()")
to fix the following build breaks

Errors:
drivers/misc/mediatek/usb/usb_rndis/u_ether.c:1221:31: error: passing const unsigned char * to parameter of type u8 * (aka unsigned char *) discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]

MTK-Commit-Id: ca0a2bfb00c6b09a2ebcf67bba932b8a292597e5

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I7c28761d3135f2eff485d8f357e460cd023dcf42