[ALPS07673475] sched/pause: mask out unsupported functions
There are some vendor hooks not supported in android-mainline, mask them
out to fix the following build breaks

Errors:
drivers/misc/mediatek/sched/eas/core_pause.c:159:10: error: implicit declaration of function pick_migrate_task is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:184:3: error: implicit declaration of function rq_relock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:197:14: error: implicit declaration of function select_fallback_rq is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:200:9: error: implicit declaration of function __migrate_task is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 9a937dd60c448668876329f750d53cc5a6750a32

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Id34726e666af57e3403b9366bbc0c90cbd841b36