[ALPS07713407] sched: fix task_running build breaks
Follow commit 0b9d46fc5ef7 ("sched: Rename task_running() to task_on_cpu()")
to replace task_running with task_on_cpu and fix the following
build breaks:

drivers/misc/mediatek/sched/fair.c:1012:7: error: call to undeclared function task_running; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/fair.c:1078:3: error: call to undeclared function task_running; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 0c2be5916257a79e1a802855511f455a87c61753

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I2279e545c498647c300c7beed3af20978416e597