[ALPS07713407] thermal: fix thermal_zone_of_device_ops build breaks
Follow commit f59ac19b7f44 ("thermal/of: Remove old OF code") to
move to new OF APIs and fix the following build breaks:

drivers/thermal/mediatek/soc_temp_lvts.c:982:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/thermal/mediatek/pmic_temp.c:127:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/thermal/mediatek/soc_temp_lvts.c:1558:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/thermal/mediatek/pmic_temp.c:165:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/thermal/mediatek/board_temp.c:237:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/thermal/mediatek/board_temp.c:363:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/thermal/mediatek/vtskin_temp.c:72:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/thermal/mediatek/vtskin_temp.c:106:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:113:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:121:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:130:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:139:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:149:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:160:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:171:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:182:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src/isp6s/../common/v1_1/imgsensor_i2c.c:193:2: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:1033:48: error: variable has incomplete type const struct thermal_zone_of_device_ops
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:1416:11: error: call to undeclared function devm_thermal_zone_of_sensor_register; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: bb84c068bd7685bdba5868f82b4204983be367b7

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Iea3e1ec4879c6456a848c9fc517fa0769354cefb