[ALPS07673475] aee: implicit declaration of init_utsname
include linux/utsname.h to fix the implicit declaration of init_utsname
build breaks:

Error:
drivers/misc/mediatek/aee/mrdump/mboot_params.c:3403:9: error: array_size macro redefined [-Werror,-Wmacro-redefined]
drivers/misc/mediatek/aee/hangdet/sched_debug.c:57:6: error: implicit declaration of function autogroup_path is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/hangdet/sched_debug.c:677:3: error: implicit declaration of function init_utsname is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/aee/hangdet/sched_debug.c:677:19: error: member reference type int is not a pointer
drivers/misc/mediatek/aee/hangdet/sched_debug.c:678:32: error: member reference type int is not a pointer
drivers/misc/mediatek/aee/hangdet/sched_debug.c:679:19: error: member reference type int is not a pointer

MTK-Commit-Id: a7f197264629c35dabb31de1d34cbd73a2860911

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I9d77fdc3d19225f1e8f1558e952edfeb0ba209d6