[ALPS07673475] tee: fix cpufreq_table_find_index_dl build breaks
commit 1f39fa0dccff ("cpufreq: Introducing CPUFREQ_RELATION_E")

By the commit message, if efficiencies is true, it only iterates efficient
frequencies, so lets set it to false to at least keep the old behaviour.

Errors:
drivers/tee/teeperf/user.c:32:51: error: too few arguments to function call, expected 3, have 2

MTK-Commit-Id: 8136fe869371ce0ebc78962ae38632eb2f7eaac2

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I2c9f3907790a3b6bf801e47550df009da0bb2bbe