[ALPS07673475] interconnect: fix sched_clock build breaks
include linux/sched/clock to fix the following build breaks

drivers/interconnect/mediatek/mmqos-hrt.c:42:20: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/interconnect/mediatek/mmqos-hrt.c:59:20: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/interconnect/mediatek/mmqos-mtk.c:363:50: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/interconnect/mediatek/mmqos-mtk.c:377:44: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 68011e085c448b38e493c17c73825a58dbdc9c34

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I4e2a61cae70ad167e29e84cc4db5b982a1ea16b5