[ALPS07673475] aee: fix kinfo_debug path
commit 094f5702db86 ("ANDROID: debug_kinfo driver, move to drivers/android")
move debug_kinfo to drivers/android, change the include path accordingly.

Error:
drivers/misc/mediatek/aee/mrdump/mrdump_helper.c:22:10: fatal error: debug_kinfo.h file not found

MTK-Commit-Id: 06bcd0ad93a09bf01601db1cd5bbb45d3d2b0fe1

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I30519c0b9208adf5cadf15b86d872d0fa0830599