[ALPS07713407] tmem: fix ffa_dev_ops build breaks
Follow commit 7aa7a9798955 ("firmware: arm_ffa: Rename ffa_dev_ops as ffa_ops")
to replace ffa_dev_ops with ffa_ops and fix the following build
errors:

drivers/misc/mediatek/trusted_mem/mtee_impl/tmem_carveout_heap.c:312:15: error: incomplete definition of type struct ffa_dev_ops
drivers/misc/mediatek/trusted_mem/mtee_impl/tmem_carveout_heap.c:341:15: error: incomplete definition of type struct ffa_dev_ops
drivers/misc/mediatek/trusted_mem/mtee_impl/tmem_carveout_heap.c:411:15: error: incomplete definition of type struct ffa_dev_ops
drivers/misc/mediatek/trusted_mem/mtee_impl/tmem_carveout_heap.c:467:15: error: incomplete definition of type struct ffa_dev_ops

MTK-Commit-Id: 965e89471531420aeaa09e9c09c63d342893b8d2

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I1bd769ce918d3b30a69dc75c1f5cb2f2792c5760