[ALPS07760999] ccmni: use netif_napi_add_weight
Use netif_napi_add_weight to fix the following build breaks:

drivers/misc/mediatek/ccmni/ccmni.c:946:4: error: too many arguments to function call, expected 3, have 4
drivers/misc/mediatek/ccmni/ccmni.c:951:4: error: too many arguments to function call, expected 3, have 4

MTK-Commit-Id: 29030c0e102db57a5897c7ec65ddb0381ba8ac18

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07760999
Feature: Kernel SI Operation
Change-Id: I2a218e67f1924988948517950b1152603a2ecb5f