[ALPS07673475] vcodec: fix implicit function dma_resv_get_excl_unlocked
Follow commit 5e9ddbdcf730 ("drm/i915: use new cursor in intel_prepare_plane_fb v2")
to fix the follow build breaks.

drivers/media/platform/mtk-vcodec/vdec/vdec_vcu_if.c:380:30: error: implicit declaration of function dma_resv_get_excl_unlocked is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-vcodec/vdec/vdec_vcu_if.c:380:22: error: incompatible integer to pointer conversion initializing struct dma_fence * with an expression of type int [-Werror,-Wint-conversion]

MTK-Commit-Id: 8cffd92b7639d59f832d59cfd067175d0836f063

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I0f8b6f9f6e107a916570b33dff64dbc3239f7aef