[ALPS07673475] blocktag: fix missing headers
include <linux/major.h> and <linux/sched/clock.h> to fix blocktag build breaks

drivers/misc/mediatek/blocktag/blocktag-core.c:179:15: error: use of undeclared identifier SCSI_DISK0_MAJOR
drivers/misc/mediatek/blocktag/blocktag-core.c:179:44: error: use of undeclared identifier BLOCK_EXT_MAJOR
drivers/misc/mediatek/blocktag/blocktag-core.c:181:20: error: use of undeclared identifier MMC_BLOCK_MAJOR
drivers/misc/mediatek/blocktag/blocktag-core.c:181:48: error: use of undeclared identifier BLOCK_EXT_MAJOR

MTK-Commit-Id: e93337c290d28da44c0ae0da951aec0e99c16002

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I7474b1d24532b5f73673d011e46f9c4cd16c3484