[ALPS07673475] kernel: implicit declaration of fix sched_clock
include linux/sched/clock.h to fix the following build breaks

drivers/misc/mediatek/blocktag/blocktag-mictx.c:22:18: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/blocktag-mictx.c:42:16: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/blocktag-mictx.c:64:19: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/blocktag-mictx.c:183:13: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/blocktag/blocktag-mictx.c:272:25: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/scsi/ufs/vendor/../ufs-mediatek.c:360:12: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:606:9: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: b81408bd4e4f8d1270cce2536f5a04e106be9df6

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I7fc6a451fe0150cfea0f53a0bb2076f0b9f16c15