[ALPS07713407] DISP: fix undeclared identifier DRM_PLANE_HELPER_NO_SCALING
Follow commit cce32e4e38c6 ("drm/atomic-helper: Remove _HELPER_ infix from DRM_PLANE_HELPER_NO_SCALING")
to rename DRM_PLANE_HELPER_NO_SCALING to DRM_PLANE_NO_SCALING and
fix the following build breaks:

drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_plane.c:365:33: error: use of undeclared identifier DRM_PLANE_HELPER_NO_SCALING
drivers/gpu/drm/mediatek/mediatek_v2/mtk_drm_plane.c:366:4: error: use of undeclared identifier DRM_PLANE_HELPER_NO_SCALING

MTK-Commit-Id: c6fc429b4c8d84c06be520a5d19b0bcda2c43e42

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I91ed6cd2ff32223c7401341370ace42e283e1940