[ALPS07713407] kernel_device_modules: fix mipi remove callback type
Follow commit 79abca2b3990 ("drm/mipi-dsi: Make remove callback return void")
to change the return type of remove functions and fix the following
build breaks:

drivers/gpu/drm/panel/panel-samsung-ana6705-cmd.c:3635:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-samsung-ana6705-cmd-fhdp.c:3250:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-hx-nt37701-dphy-cmd.c:748:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-hx-nt37701-dphy-cmd-120hz.c:897:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-truly-td4330-vdo.c:906:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-truly-td4330-cmd.c:856:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-samsung-op-cmd.c:1345:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-samsung-op-cmd-msync2.c:2685:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-truly-ft8756-vdo.c:908:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672c-cphy-vdo.c:1345:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-sc-nt36672c-vdo-120hz.c:995:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-tianma-r66451-cmd-120hz.c:956:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-tianma-r66451-cmd-120hz-wa.c:962:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-tianma-nt36672e-vdo-120hz-hfp.c:1140:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-cphy-vdo.c:1445:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-vdo-120hz.c:1629:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-vdo-144hz.c:1399:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-vdo-144hz-hfp.c:1446:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-vdo-120hz-hfp.c:1517:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-alpha-jdi-nt36672e-vdo-60hz.c:1095:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-truly-nt35595-cmd.c:1128:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-samsung-s68fc01-vdo-aod.c:1014:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-nt37801-cmd-ltpo.c:675:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-nt37801-cmd-120hz.c:1196:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-l12a-42-02-0a-dsc-cmd.c:1489:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/k6985v1_64/td2204-wqhd-amb678zy01-s6e3hc3-cmd.c:631:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-nt37801-cmd-fhd.c:1234:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/panel-nt37801-cmd-spr.c:1342:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/k6985v1_64_alpha/panel-nt37705-alpha-cmd.c:612:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]
drivers/gpu/drm/panel/mtk_drm_panel_drv_dsi.c:2803:12: error: incompatible function pointer types initializing void (*)(struct mipi_dsi_device *) with an expression of type int (struct mipi_dsi_device *) [-Werror,-Wincompatible-function-pointer-types]

MTK-Commit-Id: 415b2a0865b8dd1e75066d1c23ac9744f3a86e85

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ia3dcc1a89799cd7df2e1ba9d0626e9dc1efdd240