[ALPS07673475] eas: fix cpufreq_table_find_index_dl
commit: 1f39fa0dccff ("cpufreq: Introducing CPUFREQ_RELATION_E")
introduces CPUFREQ_RELATION_E and add an additional argument
to cpufreq_table_find_index_dl. Fix it by adding false
to existing flow.

drivers/misc/mediatek/sched/sugov/nonlinear_opp_cap.c:473:65: error: too few arguments to function call, expected 3, have 2
drivers/misc/mediatek/sched/sugov/nonlinear_opp_cap.c:481:69: error: too few arguments to function call, expected 3, have 2

MTK-Commit-Id: df232232c3757db63c87597b6eb7f6657cf483aa

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I59975f127c3510ee636f6b208a77db7e6832c4f4