[ALPS07673475] iommu: fix iommu_ops build breaks
commit 9a630a4b41a2 ("iommu: Split struct iommu_ops") moves domain
ops out of iommu_ops, change them accordingly.

errors:
drivers/iommu/mtk_iommu.c:1988:3: error: field designator domain_free does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1989:3: error: field designator attach_dev does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1990:3: error: field designator detach_dev does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1991:3: error: field designator map does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1992:3: error: field designator unmap does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1993:3: error: field designator flush_iotlb_all does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1994:3: error: field designator iotlb_sync does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1995:3: error: field designator iotlb_sync_map does not refer to any field in type const struct iommu_ops
drivers/iommu/mtk_iommu.c:1996:3: error: field designator iova_to_phys does not refer to any field in type const struct iommu_ops

MTK-Commit-Id: 950a5456eb990e9df3628a82b519e7a4222e6f08

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ie5cf9aad06c69bc02719ab7cde1c14802c3721c0