[ALPS07673475] apu: fix unannotated fall-through build breaks
Fix unannotated fall-through build breaks by adding fallthrough

drivers/misc/mediatek/apusys/power/3.0/platform/mt6886_pwr_func.c:226:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/misc/mediatek/apusys/power/2.5/common/apu-dbg.c:389:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

MTK-Commit-Id: 195da5c96ea1cb8152a4f004b6400a3c559e011e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ibe1c742e6bfe1a2dcfb6c60768e79e0dca7b6a4c