[ALPS07673475] fpsgo: fix sched_clock build breaks
include linux/sched/clock to fix the following build breaks

drivers/misc/mediatek/performance/fpsgo_v3/fpsgo_main.c:719:10: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: d2c822701398b0bdf2d04c2157a80dfd828efa69

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I5af8a8690e1179fd076dd6726f2fcecf2e1a11f3