[ALPS07673475] tee: fix DEFINE_KTHREAD_WORKER build breaks
commit 62eb29526b48 ("linux/kthread.h: remove unused macros") removes
DEFINE_KTHREAD_WORKER macro and the ut_fastcall_worker defined is not
used. So simply remove ut_fastcall_worker to fix the following build
breaks

Errors:
drivers/tee/teei/500/tz_driver/teei_client_main.c:182:1: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]
drivers/tee/teei/500/tz_driver/teei_client_main.c:182:23: error: a parameter list without types is only allowed in a function definition

MTK-Commit-Id: 5451da75e95379d08ab13018fe30e721444a3d8a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ibe25a3fa44a52ef683165f1864a4a59f74ff13a4