[ALPS07673475] ccmni: fix netif_rx_ni and ARPHRD_NONE build breaks
Replace netif_rx_ni with netif_rx
include linux/if_arp.h for ARPHRD_NONE

drivers/misc/mediatek/ccmni/ccmni.c:361:5: error: implicit declaration of function netif_rx_ni is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccmni/ccmni.c:1005:2: error: implicit declaration of function random_ether_addr is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/ccmni/ccmni.c:1081:15: error: use of undeclared identifier ARPHRD_NONE
drivers/misc/mediatek/ccmni/ccmni.c:1244:4: error: implicit declaration of function netif_rx_ni is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 4340163d3e5f605b9ebe9c7ab5690f0d1c51211a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Ifaba299da4be13955979de6be0cb689f3c6f323f