[ALPS07673475] usb: fix netif_rx_ni build breaks
With commit 2655926aea9b ("net: Remove netif_rx_any_context() and netif_rx_ni()."),
use netif_rx for all context.

Errors:
drivers/misc/mediatek/usb/usb_rndis/u_ether.c:528:12: error: implicit declaration of function netif_rx_ni is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: f2eee39c92f0359d45807a0f21f873d95fef761a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I9a05a4eadffe0875be8e46f649daa5e3dff220c7