[ALPS07673475] aee: fix statistics not found build breaks
commit ceeadb83aea2 ("sched: Make struct sched_statistics independent of fair sched class")
moves statistics out of struct sched_entity, fix the following
build breaks by using correct pointer.

i.e.,
/p->se.statistics/p->stats/

drivers/misc/mediatek/aee/hangdet/sched_debug.c:96:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:96:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:98:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:98:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:131:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:131:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:133:19: error: no member named statistics in struct sched_entity
drivers/misc/mediatek/aee/hangdet/sched_debug.c:133:19: error: no member named statistics in struct sched_entity

MTK-Commit-Id: 74999e962fb2eb36ef1c6117e137c87e7cdb627b

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I8a77d57e78b396df9ee792cc7d33f76cf66fb7c4