[ALPS07673475] 8250: fix no member named cpu in struct task_struct
commit bcf9033e5449 ("sched: move CPU field back into thread_info if THREAD_INFO_IN_TASK=y")
move cpu to thread_info, fix it accordingly.

Error:
drivers/tty/serial/8250/8250_mtk.c:1071:41: error: no member named cpu in struct task_struct
drivers/dma/mediatek/mtk-uart-apdma.c:637:42: error: no member named cpu in struct task_struct

MTK-Commit-Id: 2905d04a5fec700a8998e3700c220012fdff6351

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I508adff9c27854122220731afbd5bf045938f8a7