[ALPS07673475] aee: fix sched_clok build breaks
include linux/sched/clock to fix the following build breaks

drivers/misc/mediatek/aee/hangdet/sched_debug.c:671:14: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/mmdvfs/mtk-mmdvfs-debug.c:141:13: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:277:19: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:322:19: error: implicit declaration of function sched_clock is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: ec931ccb2dcf1fa1ee2b1b7602e5234c874dbf88

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I5ca4799afa4af99d6bb3d6256d7b4a911af80afd