[ALPS07673475] sched: fix default_attrs
Use default_groups instead of default_attrs to fix the following
build breaks:

drivers/misc/mediatek/sched/core_ctl/core_ctl.c:1036:3: error: field designator default_attrs does not refer to any field in type struct kobj_type

MTK-Commit-Id: 6054f3b63ff6e8b3758fddbd0c3cce7f3ff3c35c

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Idfd06b8582058307e8032172a858eaec3df2f7ae