[ALPS07673475] iommu: fix type specifier missing
Add type specifier to fix the following build breaks

drivers/misc/mediatek/iommu/iommu_secure.c:222:1: error: type specifier missing, defaults to int [-Werror,-Wimplicit-int]

MTK-Commit-Id: 5dcdce6df8cfc939d8483eedc90ff1d731a49702

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I5aeacd30799d7964b2964118fece36a0533e2f55