[ALPS07673475] performance: fix incomplete type struct sched_attr
include uapi/linux/sched/types.h to fix the following build breaks:

drivers/misc/mediatek/performance/fpsgo_v3/fbt/platform/fbt_cpu_platform.c:146:20: error: variable has incomplete type struct sched_attr
drivers/misc/mediatek/performance/fpsgo_v3/fpsgo_main.c:305:20: error: variable has incomplete type struct sched_attr
drivers/misc/mediatek/sched/sugov/cpufreq_sugov_main.c:834:12: error: invalid application of sizeof to an incomplete type struct sched_attr
drivers/misc/mediatek/sched/sugov/cpufreq_sugov_main.c:833:20: error: variable has incomplete type struct sched_attr

MTK-Commit-Id: ac038830896ceaa26d76158d78d87dbc18f68f1f

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Iefa4a0509bc52d9edc5bbeb046575ce7582d0bee