[ALPS07673475] sched/pause: mask out unsupported vendor hooks
There are some vendor hooks not supported in android-mainline, mask them
out to fix the following build breaks

Errors:
drivers/misc/mediatek/sched/eas/core_pause.c:617:2: error: implicit declaration of function register_trace_android_rvh_is_cpu_allowed is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:618:2: error: implicit declaration of function register_trace_android_rvh_set_cpus_allowed_ptr_locked is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:620:2: error: implicit declaration of function register_trace_android_rvh_rto_next_cpu is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:622:2: error: implicit declaration of function register_trace_android_rvh_get_nohz_timer_target is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/sched/eas/core_pause.c:626:2: error: implicit declaration of function register_trace_android_rvh_find_new_ilb is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 4b52a45adead1e35467fa103f33a57cfa5b31995

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I34654f78df61fce868ce997dd120b546b460bb3f