[ALPS07713407] iommu/mediatek: fix dma-iommu.h not found error
commit f2042ed21da7 ("iommu/dma: Make header private") so remove
the include of dma-iommu.h to fix the following build breaks:

drivers/iommu/mtk_iommu.c:14:10: fatal error: linux/dma-iommu.h file not found

MTK-Commit-Id: 65f287feef88bdb077d0b6261835301694c92150

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Id7b3ae5996be319ac41c748e97522e7250877026