[ALPS07689827] adsp: fix build error
__ioremap is missing, thus mark it.

drivers/misc/mediatek/adsp/v2/adsp_driver_v2.c:253:18: error: implicit declaration of function __ioremap is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        pdata->sysram = __ioremap(pdata->sysram_phys, pdata->sysram_size,
                        ^

MTK-Commit-Id: f5fc318785e60ddd62f82d66b251ef6f09d2b007

CR-Id: ALPS07689827
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: Ib9604c27802698596cc8ffa305ead73ad7b0147c