[ALPS07673475] cpufreq: fix incomplete type struct sched_attr
commit 1f39fa0dccff ("cpufreq: Introducing CPUFREQ_RELATION_E") introduces
CPUFREQ_RELATION_E and also changes the API of cpufreq_table_find_index_dl.

By the commit message, if efficiencies is true, it only iterates efficient
frequencies, so lets set it to false to at least keep the old behaviour.

Errors:
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_08_13_00-mainline/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/cpufreq/mediatek-cpufreq-hw.c:131:58: error: too few arguments to function call, expected 3, have 2

MTK-Commit-Id: 2269023c86a82489006f0ff44dabd85216bc30ba

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I0aebffbe70b8e6a8f5299ae4100b446bca976ad1