[ALPS07673475] eas: comment out unsupported android_rvh_schedule
Comment out android_rvh_schedule because it is not
supported in mainline now. Users can add them back when LTS out,
following Googles rule.

Errors:
drivers/misc/mediatek/sched/eas/sched_main.c:408:8: error: implicit declaration of function register_trace_android_rvh_schedule is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 806f9122d3fb132bae5ed0c9dbc98dcee1bbaece

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I9b7f74ffe916f4a031da396b23215478057637b2