[ALPS07713407] apusys: use get_random_u32
To upgrade to kernel-6.1,
follow commit de492c83cae0 ("prandom: remove unused functions")
to move to get_random_u32 and to fix the following build breaks:

drivers/misc/mediatek/apusys/mdla/common/mdla_power_ctrl.c:259:9:
error: call to undeclared function get_random_int; ISO C99 and
later do not support implicit function declarations
[-Wimplicit-function-declaration]

MTK-Commit-Id: 6f569a42b9eda726e1c2ed55f91806b98c566a29

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ie415f7d8c54d303fd1c8c89254d4b1449d610f80