[ALPS07673475] mrdump: fix stdarg.h not found build breaks
Fix the following build breaks by correct the include path:
drivers/misc/mediatek/include/mt-plat/mrdump.h:12:10: fatal error: stdarg.h file not found

MTK-Commit-Id: 9b07deeb3921f90dbbcfdfc9cf1c8d7067b320ab

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: If0c3667a5f25a7a32d4a1372776128ca6a625b39