[ALPS07673475] ISP: fix incorrect headers
commit 3056a8e936bb ("media: media-entity: Simplify media_pipeline_start()")
drops the stream_count of struct media_entity.
Fix the users of stream_count accordingly.

drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:684:30: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:927:53: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:938:52: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:948:52: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:4105:18: error: no member named stream_count in struct media_entity
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:4217:15: error: no member named stream_count in struct media_entity

MTK-Commit-Id: a287e2dcb0d3e50ca86aea2657c184ee00223593

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I7da7a5826ca0bc621724287f66b2a7bce4f9a380