[ALPS07713407] media: isp: fix no member named graph build breaks
Follow commit ae219872834a ("media: mc: entity: Rewrite media_pipeline_start()")
to use pad instead of graph and fix the build breaks:

drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-raw.c:4386:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam-raw.c:4386:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:5591:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:5594:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-raw.c:4163:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7sp/cam_legacy/mtk_cam.c:8738:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam.c:8741:25: error: no member named graph in struct media_pipeline
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam.c:6677:25: error: no member named graph in struct media_pipeline

MTK-Commit-Id: 8c915a0e8267c77c28b9ea977fde9e66a6f400bb

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I4f5eb0fae779843ebe817847655df0728723e2b3