[ALPS07713407] monitor_hang: fix vma liked list build breaks
By commit 763ecb035029 ("mm: remove the vma linked list"),
vma is removed so we have to use maple tree to fix the following
build breaks:

drivers/misc/mediatek/monitor_hang/hang_detect.c:966:26: error: no member named mmap in struct mm_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1030:14: error: no member named vm_next in struct vm_area_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1193:27: error: no member named mmap in struct mm_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1200:15: error: no member named vm_next in struct vm_area_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1201:33: error: no member named mmap in struct mm_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1254:27: error: no member named mmap in struct mm_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1261:15: error: no member named vm_next in struct vm_area_struct
drivers/misc/mediatek/monitor_hang/hang_detect.c:1262:33: error: no member named mmap in struct mm_struct

MTK-Commit-Id: 32a7267fed40ae0147b5b943a27b309ccf40cf9e

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ibcb0a99c7b6b4bd412343c7e8699504898f6dbd9