[ALPS07673475] media: fix incompatible function type build breaks
Fix the following build breaks by correct function arg.

drivers/media/platform/mtk-aie/mtk_aie_drv_isp71.c:4802:3: error: cast from int (*)(int, unsigned int, void *) to mtk_iommu_fault_callback_t (aka int (*)(int, unsigned long long, void *)) converts to incompatible function type [-Werror,-Wcast-function-type]
(mtk_iommu_fault_callback_t)FDVT_M4U_TranslationFault_callback,

MTK-Commit-Id: b6c600f6aaa39ff4335e0efe8bf0f6550b04d513

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I0fb6b60ea2f95815fa16afd9499c7cd85f1dd70d