[ALPS07689827] arm64: configs: mgk: fix build error
1. Enable CONFIG_MTK_ADVANCED_80211_MLO as we are moving to kernel-6.0
   This reverts commit 9ed5c325c0c9

2. Use CONFIG_DRM_DISPLAY_HELPER to replace CONFIG_DRM_DP_HELPER

3. Fix PINCTRL and COMMON_CLK build error

   ERROR: modpost: ../kernel/kernel_device_modules-mainline/drivers/pinctrl/mediatek pinctrl-mtk-v2: mtk_pinconf_drive_get_rev1 exported twice. Previous export was in vmlinux
   ERROR: modpost: ../kernel/kernel_device_modules-mainline/drivers/clk/mediatek/clk-common: mtk_alloc_clk_data exported twice. Previous export was in vmlinux

MTK-Commit-Id: c6d3e55aa559f481a73c93f2ab28eced560fd099

CR-Id: ALPS07689827
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: I76c5175a7b9a1011c70507061c60e76f042a00c0