[ALPS07914299] ufs: Fix build error due to ACK
error: too many arguments to function call, expected 2, have 3
     if (!ufs_is_valid_unit_desc_lun(&hba->dev_info, lun, 0)) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
           ^

MTK-Commit-Id: 6f62dae4ea2a2f3d073a92666292bb5550939b4d

CR-Id: ALPS07914299
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: I9d4a3d59e7c7c86f98b174fc73dcf64fe4649e85