[ALPS07689827] vcodec: dma_resv_add_excl_fence
commit 047a1b877ed removes dma_resv_add_excl_fence

drivers/media/platform/mtk-vcodec/mtk_vcodec_util.c:271:3: error: implicit declaration of function dma_resv_add_excl_fence is invalid in C99 [-Werror,-Wimplicit-function-declaration]

MTK-Commit-Id: 9fe6f888920aebe3d33d39ca4704a87a3cf64104

CR-Id: ALPS07689827
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: I12bc51bc693abccc61e7c8e7539bdfd47643646f