[ALPS07713407] Trustonic TEE: fix system_freezing_cnt build break
Follow commit f5d39b020809 ("freezer,sched: Rewrite core freezer logic")
to rewrute the freezer part and fix the system_freezing_cnt build
break:

drivers/tee/gud/510/MobiCoreDriver/mcp.c:247:30: error: use of undeclared identifier system_freezing_cnt

MTK-Commit-Id: 4c1314b3f100dc1f54ddf59bef35df4c05462e8a

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ie0ce0556dcb3cbc860a32ea54efb90388e4bff58