[ALPS07713407] shced: incompatible pointer types struct callback_head
Follow commit 8e5bad7dccec ("sched: Introduce struct balance_callback to avoid CFI mismatches")
to use struct balance_callback and fix the following build breaks:

drivers/misc/mediatek/sched/eas/core_pause.c:92:24: error: incompatible pointer types initializing struct callback_head * with an expression of type struct balance_callback * [-Werror,-Wincompatible-pointer-types]
drivers/misc/mediatek/sched/eas/core_pause.c:106:20: error: comparison of distinct pointer types (struct callback_head * and struct balance_callback *) [-Werror,-Wcompare-distinct-pointer-types]

MTK-Commit-Id: dcef06d163368a7a43e88704ea4a6c9e56d1039b

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: Ic2d8eeccbce9818bae824a8cf8a483effc634b1f