[ALPS08325329] use realpath
commit 392ceb5 ("kleaf: make rel_path emit an error")
causes following build error

ERROR: rel_path is deprecated. For Kleaf builds, use realpath kernel_device_modules-6.1 --relative-to kernel-6.1 instead.
Target //kernel_device_modules-6.1:mgk_64_k61_internal_modules_install.userdebug failed to build

MTK-Commit-Id: 2f80c49a2f463f02c2cc0c62a319c74fbaa78fca

CR-Id: ALPS08325329
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: Ia813e7fad54be78ee383db4a308affd7cbb1caa0