[ALPS07673475] vcodec: fix implicit-fallthrough build breaks
Fix the following unannotated fall-through errors:

drivers/media/platform/mtk-vcodec/vdec/vdec_common_if.c:654:2: error:
unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
drivers/media/platform/mtk-vcodec/vdec/vdec_vcp_if.c:640:4: error:
unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

MTK-Commit-Id: c0960d0be4efa9f7ccb77ba1ce9d5a5e9077c54f

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: Idbe617de610d52ad2b4fe62ec7e062207d4adde6