[ALPS07673475] v4l2: fix async API change build breaks
commit 3c8c15391481 ("media: v4l: async: Rename async nf functions, clean up long lines")
changes async API names, fix it by:

s/<v4l2_async_notifier_add_fwnode_remote_subdev>/v4l2_async_nf_add_fwnode_remote/g
s/<v4l2_async_notifier_add_fwnode_subdev>/v4l2_async_nf_add_fwnode/g
s/<v4l2_async_notifier_add_i2c_subdev>/v4l2_async_nf_add_i2c/g
s/<__v4l2_async_notifier_add_subdev>/__v4l2_async_nf_add_subdev/g
s/<v4l2_async_notifier_parse_fwnode_endpoints>/v4l2_async_nf_parse_fwnode_endpoints/g
s/<v4l2_async_notifier_cleanup>/v4l2_async_nf_cleanup/g
s/<v4l2_async_notifier_unregister>/v4l2_async_nf_unregister/g
s/<v4l2_async_notifier_register>/v4l2_async_nf_register/g
s/<v4l2_async_notifier_init>/v4l2_async_nf_init/g
s/<__v4l2_async_notifier_add_fwnode_subdev>/__v4l2_async_nf_add_fwnode/g

commit 6a7bdd89f50d ("media: v4l2-mediabus: Use structures to describe bus configuration")
drop the use of V4L2_MBUS_CSI2_xx_LANE, fix it accordingly.

drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1104:10: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1104:18: error: use of undeclared identifier V4L2_MBUS_CSI2_1_LANE
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1106:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1106:23: error: use of undeclared identifier V4L2_MBUS_CSI2_2_LANE
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1108:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1108:23: error: use of undeclared identifier V4L2_MBUS_CSI2_3_LANE
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1110:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1110:23: error: use of undeclared identifier V4L2_MBUS_CSI2_4_LANE
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1725:2: error: implicit declaration of function v4l2_async_notifier_init is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1726:8: error: implicit declaration of function v4l2_async_notifier_parse_fwnode_endpoints is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1732:8: error: implicit declaration of function v4l2_async_notifier_register is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1742:2: error: implicit declaration of function v4l2_async_notifier_cleanup is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1751:2: error: implicit declaration of function v4l2_async_notifier_unregister is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7_1/cam/mtk_cam-seninf-drv.c:1752:2: error: implicit declaration of function v4l2_async_notifier_cleanup is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1243:10: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1243:18: error: use of undeclared identifier V4L2_MBUS_CSI2_1_LANE
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1245:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1245:23: error: use of undeclared identifier V4L2_MBUS_CSI2_2_LANE
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1247:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1247:23: error: use of undeclared identifier V4L2_MBUS_CSI2_3_LANE
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1249:15: error: no member named flags in struct v4l2_mbus_config
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1249:23: error: use of undeclared identifier V4L2_MBUS_CSI2_4_LANE
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1995:2: error: implicit declaration of function v4l2_async_notifier_init is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:1996:8: error: implicit declaration of function v4l2_async_notifier_parse_fwnode_endpoints is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2002:8: error: implicit declaration of function v4l2_async_notifier_register is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/imgsys/mtk_imgsys-v4l2.c:1669:3: error: implicit declaration of function hash_add is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/imgsys/mtk_imgsys-v4l2.c:1742:4: error: implicit declaration of function hash_del is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2012:2: error: implicit declaration of function v4l2_async_notifier_cleanup is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2021:2: error: implicit declaration of function v4l2_async_notifier_unregister is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/media/platform/mtk-isp/camsys/isp7s/cam_legacy/mtk_cam-seninf-drv.c:2022:2: error: implicit declaration of function v4l2_async_notifier_cleanup is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:146:19: error: implicit declaration of function __v4l2_async_notifier_add_fwnode_subdev is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:146:17: error: incompatible integer to pointer conversion assigning to struct v4l2_async_subdev * from int [-Werror,-Wint-conversion]
drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:191:2: error: implicit declaration of function v4l2_async_notifier_init is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:246:7: error: implicit declaration of function v4l2_async_notifier_register is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/lens/vcm/v4l2/media/mtk-composite.c:268:2: error: implicit declaration of function v4l2_async_notifier_unregister is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/flashlight/mtk-composite.c:150:19: error: implicit declaration of function __v4l2_async_notifier_add_fwnode_subdev is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/flashlight/mtk-composite.c:150:17: error: incompatible integer to pointer conversion assigning to struct v4l2_async_subdev * from int [-Werror,-Wint-conversion]
drivers/misc/mediatek/flashlight/mtk-composite.c:232:2: error: implicit declaration of function v4l2_async_notifier_init is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/flashlight/mtk-composite.c:237:7: error: implicit declaration of function v4l2_async_notifier_register is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/flashlight/mtk-composite.c:259:2: error: implicit declaration of function v4l2_async_notifier_unregister is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/flashlight/mtk-composite.c:260:2: error: implicit declaration of function v4l2_async_notifier_cleanup is invalid in C99 [-Werror,-Wimplicit-function-declaration]
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:817:11: error: no member named flags in struct v4l2_mbus_config
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:817:19: error: use of undeclared identifier V4L2_MBUS_CSI2_1_LANE
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:820:11: error: no member named flags in struct v4l2_mbus_config
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:820:19: error: use of undeclared identifier V4L2_MBUS_CSI2_2_LANE
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:823:11: error: no member named flags in struct v4l2_mbus_config
drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:823:19: error: use of undeclared identifier V4L2_MBUS_CSI2_3_LANE
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_01_13_00-latest/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:826:11: error: no member named flags in struct v4l2_mbus_config
/mfs/mtkslt1067/mtk04267/CAS_REAL/alps-dev-t0.mp1-k515-gkimixbuild-dj--2022_08_01_13_00-latest/merged/kernel-mainline/../kernel/kernel_device_modules-mainline/drivers/misc/mediatek/imgsensor/src-v4l2/adaptor-drv.c:826:19: error: use of undeclared identifier V4L2_MBUS_CSI2_4_LANE

MTK-Commit-Id: 60595d735a3e5975c5102578c823b61557112317

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I6bba61eff78d1515d68de8b8de3bea536909f359