[ALPS07673475] mmc: fix incompatible pointer types build breaks
commit b71597edfaad ("mmc: core: improve API to make clear
mmc_hw_reset is for cards")
changes the API of mmc_hw_reset(), the commit to fix the following
build breaks:

Errors:
drivers/mmc/host/mtk-mmc.c:2175:21: error: incompatible pointer types passing struct mmc_host * to parameter of type struct mmc_
card * [-Werror,-Wincompatible-pointer-types]

MTK-Commit-Id: 1adcb2b945391fd9ddf9039e19ccea5fe0c7c844

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I870900eb4738f7d60ec4052e453660b1458402b8