[ALPS07673475] ccci: fix default_attrs
Use default_groups instead of default_attrs to fix the following
build breaks:

drivers/misc/mediatek/ccci_util/ccci_util_lib_sys.c:363:3: error: field designator default_attrs does not refer to any field in type struct kobj_type
drivers/misc/mediatek/eccci/fsm/ccci_fsm_sys.c:96:3: error: field designator default_attrs does not refer to any field in type struct kobj_type
drivers/misc/mediatek/eccci/fsm/modem_sys1.c:1427:3: error: field designator default_attrs does not refer to any field in type struct kobj_type

MTK-Commit-Id: 48dcaae6b600b5d98c4d720379d5dfe0c3ae61be

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07673475
Feature: Kernel SI Operation
Change-Id: I7601fda7a84f701ca71d40c6be5e9431e84edd78