[ALPS07713407] ccmni: fix netif_napi_add build breaks
Follow commit b48b89f9c189 ("net: drop the weight argument from netif_napi_add")
to remove the weight from netif_napi_add to fix the following build
breaks:

drivers/misc/mediatek/ccmni/ccmni.c:946:4: error: too many arguments to function call, expected 3, have 4
drivers/misc/mediatek/ccmni/ccmni.c:951:4: error: too many arguments to function call, expected 3, have 4

MTK-Commit-Id: daa1e03ed4fb682071ec15e13aa3aba4398ab327

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: If2368e70ec412975c9c0a6ed5730e5447426ed6e